### ISSUE TITLE
Auth failure

### ISSUE THREAD

**Issue by Elf36** [nmaves/passport-slack-oauth2#8]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wiki@2.5.201
npm ERR! Found: graphql@15.3.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"15.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
npm ERR! node_modules/apollo-link-persisted-queries
npm ERR!   dev apollo-link-persisted-queries@"0.2.2" from the root project
npm ERR!

**Comment by nmaves** [comment]
This does not appear to have anything to do with this library.
